CREATE TABLE [dbo].[Coaches]
(
	[ID]	INT IDENTITY (1,1)	NOT NULL,
	[NAME]	NVARCHAR (MAX)		NOT NULL,
	CONSTRAINT [PK_dbo.Coaches]	PRIMARY KEY CLUSTERED ([ID] ASC)
);

CREATE TABLE [dbo].[Teams]
(
	[ID]		INT IDENTITY (1,1)	NOT NULL,
	[NAME]		NVARCHAR (MAX)		NOT NULL,
	[COACHID]	INT					NOT NULL
	CONSTRAINT [PK_dbo.Teams] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_dbo.Teams_dbo.Coaches_ID] FOREIGN KEY ([COACHID]) REFERENCES [dbo].[Coaches] ([ID])
);

CREATE TABLE [dbo].[Athletes]
(
	[ID]		INT IDENTITY (1,1)	NOT NULL,
	[NAME]		NVARCHAR (MAX)		NOT NULL,
	[GENDER]	NVARCHAR (MAX)		NOT NULL,
	[AGE]		INT					NOT NULL
	CONSTRAINT [PK_dbo.Athletes] PRIMARY KEY CLUSTERED ([ID] ASC)
);

CREATE TABLE [dbo].[TeamRosters]
(
	[ID]		INT IDENTITY (1,1)	NOT NULL,
	[TEAMID]	INT					NOT NULL,
	[ATHLETEID]	INT					NOT NULL
	CONSTRAINT [PK_dbo.TeamRosters] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_dbo.TeamRosters_dbo.Teams_ID] FOREIGN KEY ([TEAMID]) REFERENCES [dbo].[Teams] ([ID]),
	CONSTRAINT [FK_dbo.TeamRosters_dbo.Athletes_ID] FOREIGN KEY ([ATHLETEID]) REFERENCES [dbo].[Athletes] ([ID])
);

CREATE TABLE [dbo].[Meets] 
(
	[ID]		INT IDENTITY (1,1)	NOT NULL,
	[LOCATION]	NVARCHAR (MAX)		NOT NULL,
	[DATE]		DATETIME			NOT NULL
	CONSTRAINT [PK_dbo.Meets] PRIMARY KEY CLUSTERED ([ID] ASC)
);

CREATE TABLE [dbo].[TeamMeets]
(
	[ID]		INT IDENTITY (1,1)	NOT NULL,
	[TEAMID]	INT					NOT NULL,
	[MEETID]	INT					NOT NULL
	CONSTRAINT [PK_dbo.TeamMeets] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_dbo.TeamMeets_dbo.Teams_ID] FOREIGN KEY ([TEAMID]) REFERENCES [dbo].[Teams] ([ID]),
	CONSTRAINT [FK_dbo.TeamMeets_dbo.Meets_ID] FOREIGN KEY ([MEETID]) REFERENCES [dbo].[Meets] ([ID])
);

CREATE TABLE [dbo].[Events]
(
	[ID]		INT IDENTITY (1,1)	NOT NULL,
	[DISTANCE]	INT					NOT NULL,
	[STROKE]	NVARCHAR (MAX)		NOT NULL,
	[AGEGROUP]	NVARCHAR (MAX)		,
	[GENDER]	NVARCHAR (MAX)		NOT NULL,
	[MEETID]	INT					NOT NULL
	CONSTRAINT [PK_dbo.Events] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_dbo.Events_dbo.Meets_ID] FOREIGN KEY ([MEETID]) REFERENCES [dbo].[Meets] ([ID])
);

CREATE TABLE [dbo].[Results]
(
	[ID]		INT IDENTITY (1,1)	NOT NULL,
	[EVENTID]	INT					NOT NULL,
	[ATHLETEID]	INT					NOT NULL,
	[TIME]		FLOAT				NOT NULL
	CONSTRAINT [PK_dbo.Results] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_dbo.Results_dbo.Events_ID] FOREIGN KEY ([EVENTID]) REFERENCES [dbo].[Events] ([ID]),
	CONSTRAINT [FK_dbo.Results_dbo.Athletes_ID] FOREIGN KEY ([ATHLETEID]) REFERENCES [dbo].[Athletes] ([ID])
);